### ISSUE TITLE
[BUG] pandas frequency W-WED in `ForecastingHorizon` causes failure in `AutoETS.predict`

### ISSUE THREAD

**Issue by asksteph** [alan-turing-institute/sktime#1405]
**Describe the bug**
 I have a weekly dataset with W-WED frequency that I want to train an AutoETS model on. The predict step throws an error when it does not understand this datetime frequency.

**To Reproduce**

```python
import numpy as np
import pandas as pd

# play example: 2 years of weekly data
train = pd.Series(np.random.uniform(low=2000, high=7000, size=(104,)), index=pd.date_range("2019-01-02", freq="W-WED", periods=104))

# setup AutoETS model
from sktime.forecasting.ets import AutoETS
forecaster = AutoETS(auto=True, sp=52, n_jobs=-1, restrict=True)
forecaster.fit(train)
pred = forecaster.predict(np.arange(1, 27)) # <---- this step throws the error
```

**Expected behavior**
 I expect the model to be trained on the weekly data and to return predictions for the requested forecast horizon.

**Additional context**
 If I set my datetime index to None, it will complain there is no freq supplied. But it does not understand the weekly index, so I am stuck.

**Versions**

System:
    python: 3.7.11 (default, Jul 27 2021, 09:42:29) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\szipk\anaconda3\envs\py37\python.exe
   machine: Windows-10-10.0.19041-SP0

Python dependencies:
          pip: 21.0.1
   setuptools: 49.6.0.post20200925
      sklearn: 0.24.2
       sktime: 0.7.0
  statsmodels: 0.12.2
        numpy: 1.19.2
        scipy: 1.6.2
       Cython: 0.29.24
       pandas: 1.3.2
   matplotlib: 3.4.2
       joblib: 1.0.1
        numba: 0.53.1
     pmdarima: 1.8.2
      tsfresh: 0.18.0

**Comment by aiwalter** [comment]
Hi @asksteph , I think you cant use `np` inside `predict` as `fh`. Rather use a `list` or `ForecastingHorizon`. Otherwise pls provide error.

**Comment by asksteph** [comment]
I tried several fh conventions from the example in https://github.com/alan-turing-institute/sktime/blob/main/examples/01_forecasting.ipynb. Neither the numpy, list, nor ForecastingHorizon work. I don't think it's an issue with the forecast horizon. 

```
import numpy as np
import pandas as pd

# 2 years of weekly data
train = pd.Series(np.random.uniform(low=2000, high=7000, size=(104,)), index=pd.date_range("2019-01-02", freq="W-WED", periods=104))

# forecast horizon
from sktime.forecasting.base import ForecastingHorizon
fh = ForecastingHorizon(pd.date_range("2021-01-06", periods=26, freq="W-WED"), is_relative=False)

# setup AutoETS model
from sktime.forecasting.ets import AutoETS
forecaster = AutoETS(auto=True, sp=52, n_jobs=-1, restrict=True)
forecaster.fit(train)
pred = forecaster.predict(fh) # <---- this step throws the error
```

Here's the error message:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_7048/1928607663.py in <module>
      3 forecaster = AutoETS(auto=True, sp=52, n_jobs=-1, restrict=True)
      4 forecaster.fit(train)
----> 5 pred = forecaster.predict(fh)

~\anaconda3\envs\py37\lib\site-packages\sktime\forecasting\base\_base.py in predict(self, fh, X, return_pred_int, alpha)
    156         # alpha = check_alpha(alpha)
    157 
--> 158         return self._predict(self.fh, X, return_pred_int=return_pred_int, alpha=alpha)
    159 
    160     def fit_predict(

~\anaconda3\envs\py37\lib\site-packages\sktime\forecasting\base\adapters\_statsmodels.py in _predict(self, fh, X, return_pred_int, alpha)
     78         # statsmodels requires zero-based indexing starting at the
     79         # beginning of the training series when passing integers
---> 80         start, end = fh.to_absolute_int(self._y.index[0], self.cutoff)[[0, -1]]
     81         y_pred = self._fitted_forecaster.predict(start, end)
     82 

~\anaconda3\envs\py37\lib\site-packages\sktime\forecasting\base\_fh.py in to_absolute_int(self, start, cutoff)
    322 
    323         if isinstance(absolute, (pd.PeriodIndex, pd.DatetimeIndex)):
--> 324             integers = _coerce_duration_to_int(integers, freq=_get_freq(cutoff))
    325 
    326         return self._new(integers, is_relative=False)

~\anaconda3\envs\py37\lib\site-packages\sktime\utils\datetime.py in _coerce_duration_to_int(duration, freq)
     43         m = re.match(r"(?P<count>\d*)(?P<unit>[a-zA-Z]+)$", freq)
     44         if not m:
---> 45             raise ValueError("pandas frequency %s not understood." % freq)
     46         count, unit = m.groups()
     47         count = 1 if not count else int(count)

ValueError: pandas frequency W-WED not understood.
```
Let me know what you think. Thank you!

**Comment by aiwalter** [comment]
as a hotfix, I did `train.to_period()` which worked well. Generally `sktime` works best with `pd.PeriodIndex`.

**Comment by fkiraly** [comment]
I believe this is related to issue #866 and the proposed fix in #867.

I think the fix should still work, but the PR was abandoned by its author before it was ready to merge.
Perhaps someone could take this on?

FYI @xiaobenbenecho in case you are still watching sktime.

**Comment by asksteph** [comment]
The hotfix worked. Thank you.

**Comment by xiaobenbenecho** [comment]
Yes. Still watching. Just created another merge request #1409.

Franz Király ***@***.***> 于2021年9月11日周六 下午6:14写道：

**Comment by fkiraly** [comment]
Thanks, @xiaobenbenecho!

The fix looks reasonable, but you need to make sure the docstring and code quality (code formatting) checks pass. I believe this was also the issue with your last PR.

This is not a big thing, but it would block the PR from getting merged. If you would like to be shown how to set this up (you see it once then you know how to do it), feel free to join our regular collaboration sessions, next ones are Fridays 1pm UTC on discord.

**Comment by xiaobenbenecho** [comment]
Thanks. Franz. Tried another push to fix the code and doc quality issue by
following the hints of the error. Please review again to see whether that
works.

If not, would you mind providing the Discord conversation name for me
to join, please? Best

Franz Király ***@***.***> 于2021年9月12日周日 上午10:37写道：

**Comment by fkiraly** [comment]
ah, still failing - make sure you have all the sktime linters installed locally, see developer instructions.

For getting on discord, search for this button on the `sktime` landing page
![image](https://user-images.githubusercontent.com/7985502/132985143-44f473b7-e6bc-40b9-a956-f9087427358b.png)
the collaboration sessions are usually in the meet-up channel

**Comment by fkiraly** [comment]
This is now fixed via https://github.com/alan-turing-institute/sktime/pull/1409, thanks @xiaobenbenecho!

FYI @asksteph

**Comment by fkiraly** [comment]
@asksteph, there are two options:

* wait until the next stable release, which is version 0.8.1 or 0.9.0. The fix will be included with that release.
This happens usually in few weeks to month cycles, so sometime mid of Oct to mid Nov probably.
* install the development version, see instructions here:
https://www.sktime.org/en/stable/installation.html
this will include the fix (and all latest changes), but there is a small risk that it has instabilities which a release version wouldn´t have.

**Comment by asksteph** [comment]
This update didn't fix my error. The section that causes the error is in lines 43-45 for the  _coerce_duration_to_int function of datetime.py.  If I run my sample code, it would still return this following error:

~\anaconda3\envs\py37\lib\site-packages\sktime\utils\datetime.py in _coerce_duration_to_int(duration, freq)
     43         m = re.match(r"(?P<count>\d*)(?P<unit>[a-zA-Z]+)$", freq)
     44         if not m:
---> 45             raise ValueError("pandas frequency %s not understood." % freq)
     46         count, unit = m.groups()
     47         count = 1 if not count else int(count)

ValueError: pandas frequency W-WED not understood.

**Comment by fkiraly** [comment]
indeed, it does not seem fixed by the PR.

**Comment by fkiraly** [comment]
@aiwalter, @xiaobenbenecho, FYI

**Comment by fkiraly** [comment]
I haven't fully looked into this function, but should the regular expression maybe be
`re.match(r"(?P<count>\d*)(?P<unit>[a-zA-Z]+)[-[a-zA-Z]*]*$", freq)`

That way, anything behind a single dash would be ignored.

**Comment by fkiraly** [comment]
(sorry for the pull-in, @mloning, @xiaobenbenecho, see above - the bug seems to be resolved and I got confused)

**Comment by asksteph** [comment]
Would you please show your list of library versions, where this sample code runs successfully? I've downloaded the latest sktime code from Github, but it still doesn't like the W-WED frequency. I think the fix parses the weekly frequency string and takes the first part "W" but if that is recognized as the frequency, it defaults to W-SUN dates and not the original Wednesday dates (see the last line in the below error message).

Perhaps it's the pandas version? Here are my library versions. 

System:
    python: 3.8.10 (default, May 19 2021, 13:12:57) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\szipk\miniconda3\python.exe
   machine: Windows-10-10.0.19042-SP0

Python dependencies:
          pip: 21.1.3
   setuptools: 49.6.0.post20210108
      sklearn: 0.24.2
       sktime: 0.8.0
  statsmodels: 0.12.2
        numpy: 1.19.5
        scipy: 1.7.1
       Cython: 0.29.24
       pandas: 1.3.3
   matplotlib: 3.4.3
       joblib: 1.1.0
        numba: 0.54.1
     pmdarima: 1.8.2
      tsfresh: 0.17.0

Please list yours. Thank you!  

Here's the error:
```python
C:\Users\szipk\miniconda3\envs\skt\lib\site-packages\sktime\utils\datetime.py:65: FutureWarning: Timestamp.freqstr is deprecated and will be removed in a future version.
  if hasattr(x, "freqstr"):
C:\Users\szipk\miniconda3\envs\skt\lib\site-packages\sktime\utils\datetime.py:66: FutureWarning: Timestamp.freqstr is deprecated and will be removed in a future version.
  if x.freqstr is None:
C:\Users\szipk\miniconda3\envs\skt\lib\site-packages\sktime\utils\datetime.py:68: FutureWarning: Timestamp.freqstr is deprecated and will be removed in a future version.
  elif "-" in x.freqstr:
C:\Users\szipk\miniconda3\envs\skt\lib\site-packages\sktime\utils\datetime.py:69: FutureWarning: Timestamp.freqstr is deprecated and will be removed in a future version.
  return x.freqstr.split("-")[0]

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_20452/3478170202.py in <module>
      9 forecaster = AutoETS(auto=True, sp=52, n_jobs=-1, restrict=True)
     10 forecaster.fit(train)
---> 11 pred = forecaster.predict(np.arange(1, 27)) # <---- this step throws the error

~\miniconda3\envs\skt\lib\site-packages\sktime\forecasting\base\_base.py in predict(self, fh, X, return_pred_int, alpha)
    198         # alpha = check_alpha(alpha)
    199 
--> 200         y_pred = self._predict(
    201             self.fh,
    202             X=X_inner,

~\miniconda3\envs\skt\lib\site-packages\sktime\forecasting\base\adapters\_statsmodels.py in _predict(self, fh, X, return_pred_int, alpha)
     90         # statsmodels forecasts all periods from start to end of forecasting
     91         # horizon, but only return given time points in forecasting horizon
---> 92         return y_pred.loc[fh.to_absolute(self.cutoff).to_pandas()]
     93 
     94     def get_fitted_params(self):

~\miniconda3\envs\skt\lib\site-packages\pandas\core\indexing.py in __getitem__(self, key)
    929 
    930             maybe_callable = com.apply_if_callable(key, self.obj)
--> 931             return self._getitem_axis(maybe_callable, axis=axis)
    932 
    933     def _is_scalar_access(self, key: tuple):

~\miniconda3\envs\skt\lib\site-packages\pandas\core\indexing.py in _getitem_axis(self, key, axis)
   1151                     raise ValueError("Cannot index with multidimensional key")
   1152 
-> 1153                 return self._getitem_iterable(key, axis=axis)
   1154 
   1155             # nested tuple slicing

~\miniconda3\envs\skt\lib\site-packages\pandas\core\indexing.py in _getitem_iterable(self, key, axis)
   1091 
   1092         # A collection of keys
-> 1093         keyarr, indexer = self._get_listlike_indexer(key, axis)
   1094         return self.obj._reindex_with_indexers(
   1095             {axis: [keyarr, indexer]}, copy=True, allow_dups=True

~\miniconda3\envs\skt\lib\site-packages\pandas\core\indexing.py in _get_listlike_indexer(self, key, axis)
   1312             keyarr, indexer, new_indexer = ax._reindex_non_unique(keyarr)
   1313 
-> 1314         self._validate_read_indexer(keyarr, indexer, axis)
   1315 
   1316         if needs_i8_conversion(ax.dtype) or isinstance(

~\miniconda3\envs\skt\lib\site-packages\pandas\core\indexing.py in _validate_read_indexer(self, key, indexer, axis)
   1372                 if use_interval_msg:
   1373                     key = list(key)
-> 1374                 raise KeyError(f"None of [{key}] are in the [{axis_name}]")
   1375 
   1376             not_found = list(ensure_index(key)[missing_mask.nonzero()[0]].unique())

KeyError: "None of [DatetimeIndex(['2021-01-03', '2021-01-10', '2021-01-17', '2021-01-24',\n               
'2021-01-31', '2021-02-07', '2021-02-14', '2021-02-21',\n               
'2021-02-28', '2021-03-07', '2021-03-14', '2021-03-21',\n               
'2021-03-28', '2021-04-04', '2021-04-11', '2021-04-18',\n               
'2021-04-25', '2021-05-02', '2021-05-09', '2021-05-16',\n               
'2021-05-23', '2021-05-30', '2021-06-06', '2021-06-13',\n               
'2021-06-20', '2021-06-27'],\n              
dtype='datetime64[ns]', freq='W-SUN')] are in the [index]"
```

**Comment by asksteph** [comment]
Thank you for isolating the root cause. Getting relative forecasting horizon to work would be immensely useful.

**Comment by fkiraly** [comment]
This is now closed with the PR #1830 that fixes the root cause issue #1523 and hence should also fix this specific consequence using `AutoETS`.

Thanks for reporting, @asksteph, and thanks for fixing, @eenticott-shell.
The fix will be available from version 0.10.0 onwards.
